#!/bin/bash
# Script to display formatted user information from /etc/passwd
while IFS=':' read -r user pass uid gid gecos home shell; do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell."
  echo "User ID's place is protected by the passcode $pass, more info about the user here: $gecos"
  echo "" # Add an extra newline for better readability
done < /etc/passwd
