#!/bin/bash
# This script displays "Best School" 10 times using a while loop, adding "Hi" on the 9th iteration.
i=1
while [ $i -le 10 ]; do
  if [ $i -eq 9 ]; then  # Check if it's the 9th iteration
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$((i + 1))
done
