#!/bin/bash
# Script to display numbers 1-20 with special messages using while and case.
i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)  # Default case for all other numbers
      echo "$i"
      ;;
  esac
  i=$((i + 1))
done
