#!/bin/bash
# Script to check information about the "school" file.
if [ -f "school" ]; then  # Check if the file exists and is a regular file
  echo "school file exists"

  if [ -s "school" ]; then # Check if the file is NOT empty (size > 0)
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
  echo "school is a regular file"

else
  echo "school file does not exist"
fi
