#!/usr/bin/env bash
# script that displays the PID, along with the process name, of processes whose name contain the word bash
# shellcheck disable=SC2009
for pid in /proc/[0-9]*; do
  if grep -q "bash" "$pid/status" 2>/dev/null; then
    echo "$(basename "$pid") bash"
  fi
done

